[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "streamlit run src/app.py --server.address=0.0.0.0 --server.port=8501"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3